In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create and read 

#### 1D Array 

In [3]:
arr1 = np.array([1 , 2, 3 , 4 , 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape()

TypeError: 'tuple' object is not callable

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndin

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

#### 2D Array 

In [11]:
arr2 = np.array([[1,4 ,5] , [6, 7 , 4]])

In [12]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.size

6

#### 3D Array 

In [16]:
arr3 = np.array([[[1, 4, 5],
      [6, 7, 4]] , [[3 , 5, 7] , [6 , 7, 8]]])


In [17]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 7],
        [6, 7, 8]]])

### 

In [18]:
arr3.ndim

3

In [19]:
arr3.shape

(2, 2, 3)

### Create Random array 

In [1]:
randarr = np.random.rand(3 , 2, 3)
randarr

NameError: name 'np' is not defined