In [1]:
import numpy as np

In [2]:
randarr = np.random.rand(3,2,3)
randarr

array([[[0.56680896, 0.02458132, 0.86375532],
        [0.87177885, 0.85304491, 0.23515208]],

       [[0.73873546, 0.51657381, 0.04301768],
        [0.04001257, 0.28731892, 0.35095153]],

       [[0.52226639, 0.65263518, 0.22188849],
        [0.63728494, 0.45167114, 0.35335466]]])

In [3]:
randarr.dtype

dtype('float64')

In [4]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
zeros.ndim

3

In [7]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [8]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
ones[0][1]

array([1., 1., 1.])

In [15]:
ones[0:3]

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
ones[-1]

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)


In [19]:
a1

array([[[0.4175753 , 0.91722484],
        [0.27252898, 0.81605162],
        [0.87510721, 0.29843843]],

       [[0.97734476, 0.13819769],
        [0.45133859, 0.9980756 ],
        [0.25527055, 0.87550867]]])

In [20]:
a2

array([[[4.40228991e-01, 5.22797556e-01],
        [3.83348062e-01, 6.23943757e-01],
        [5.83742569e-01, 9.47101406e-04]],

       [[4.65708669e-01, 3.53685570e-01],
        [1.24905301e-01, 3.06933496e-01],
        [5.39281012e-01, 9.75304407e-01]]])

In [21]:
np.add(a1 , a2)

array([[[0.85780429, 1.4400224 ],
        [0.65587705, 1.43999538],
        [1.45884978, 0.29938553]],

       [[1.44305343, 0.49188326],
        [0.57624389, 1.3050091 ],
        [0.79455156, 1.85081308]]])

In [22]:
np.subtract(a1,a2)

array([[[-0.02265369,  0.39442728],
        [-0.11081908,  0.19210786],
        [ 0.29136464,  0.29749133]],

       [[ 0.51163609, -0.21548788],
        [ 0.32643329,  0.69114211],
        [-0.28401046, -0.09979573]]])

In [23]:
np.divide(a1,a2)

array([[[  0.94854111,   1.7544551 ],
        [  0.71091786,   1.30789292],
        [  1.49913207, 315.10715255]],

       [[  2.09861836,   0.39073601],
        [  3.61344627,   3.25176501],
        [  0.47335349,   0.89767735]]])

In [24]:
np.multiply(a1,a2)

array([[[1.83828751e-01, 4.79522905e-01],
        [1.04473458e-01, 5.09170314e-01],
        [5.10837329e-01, 2.82651454e-04]],

       [[4.55157928e-01, 4.88785289e-02],
        [5.63745825e-02, 3.06342834e-01],
        [1.37662560e-01, 8.53887467e-01]]])

### Satistical Operation

In [25]:
sqrt = np.sqrt(25)
abs = np.abs(-45)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [26]:
sqrt

np.float64(5.0)

In [27]:
abs

np.int64(45)

In [28]:
power

np.int64(256)

In [29]:
mins

np.float64(0.1381976901887081)

In [30]:
maxs

np.float64(0.9753044070882051)

### Updating the value

In [32]:
a1[0 ,0 ,1] = 67

In [33]:
a1

array([[[ 0.4175753 , 67.        ],
        [ 0.27252898,  0.81605162],
        [ 0.87510721,  0.29843843]],

       [[ 0.97734476,  0.13819769],
        [ 0.45133859,  0.9980756 ],
        [ 0.25527055,  0.87550867]]])

In [36]:
a1.sort()
a1

array([[[ 0.4175753 , 67.        ],
        [ 0.27252898,  0.81605162],
        [ 0.29843843,  0.87510721]],

       [[ 0.13819769,  0.97734476],
        [ 0.45133859,  0.9980756 ],
        [ 0.25527055,  0.87550867]]])

In [35]:
a1

array([[[ 0.4175753 , 67.        ],
        [ 0.27252898,  0.81605162],
        [ 0.29843843,  0.87510721]],

       [[ 0.13819769,  0.97734476],
        [ 0.45133859,  0.9980756 ],
        [ 0.25527055,  0.87550867]]])

In [37]:
a1.shape

(2, 3, 2)

In [39]:
a3 = a1.reshape((2,2,2))
a3

ValueError: cannot reshape array of size 12 into shape (2,2,2)

### Apending and Inserting

In [40]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
new = np.ones((3,2,3))
new

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
append = np.append(zeros , new , axis=0)
append

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
insert = np.insert(zeros, 1 , new  , axis = 0)
insert

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete 

In [1]:
arr5 = np.delete(append , 0, axis=1)


NameError: name 'np' is not defined

In [2]:
arr5

NameError: name 'arr5' is not defined